// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class OrbeResources
{
        public const string achievement_beat_stage_810_time = "CgkIlq3pg48YEAIQDw"; // <GPGSID>
        public const string achievement_beat_stage_11_time = "CgkIlq3pg48YEAIQCA"; // <GPGSID>
        public const string achievement_beat_stage_29_time = "CgkIlq3pg48YEAIQCQ"; // <GPGSID>
        public const string achievement_beat_stage_43_time = "CgkIlq3pg48YEAIQCw"; // <GPGSID>
        public const string achievement_beat_stage_54_time = "CgkIlq3pg48YEAIQDA"; // <GPGSID>
        public const string achievement_clear_world_1 = "CgkIlq3pg48YEAIQAA"; // <GPGSID>
        public const string achievement_clear_world_2 = "CgkIlq3pg48YEAIQAQ"; // <GPGSID>
        public const string achievement_clear_world_3 = "CgkIlq3pg48YEAIQAg"; // <GPGSID>
        public const string achievement_clear_world_4 = "CgkIlq3pg48YEAIQAw"; // <GPGSID>
        public const string achievement_clear_world_5 = "CgkIlq3pg48YEAIQBA"; // <GPGSID>
        public const string achievement_clear_world_6 = "CgkIlq3pg48YEAIQBQ"; // <GPGSID>
        public const string achievement_clear_world_7 = "CgkIlq3pg48YEAIQBg"; // <GPGSID>
        public const string achievement_clear_world_8 = "CgkIlq3pg48YEAIQBw"; // <GPGSID>
        public const string achievement_beat_stage_35_time = "CgkIlq3pg48YEAIQCg"; // <GPGSID>
        public const string achievement_beat_stage_79_time = "CgkIlq3pg48YEAIQDg"; // <GPGSID>
        public const string achievement_beat_stage_67_time = "CgkIlq3pg48YEAIQDQ"; // <GPGSID>

}

